#!/bin/bash

if [ "$1" == "" ]; then
        echo "admin update X i3 gnome gdmon omz dev fixclock neofetch"
fi

if [ "$1" == "admin" ]; then
  cp devprep /home/v/devprep.sh
  chown v:v /home/v/devprep.sh
fi

if [ "$1" == "update" ]; then
	sudo apt update -y
	sudo apt upgrade -y
fi

if [ "$1" == "X" ]; then
        sudo apt install xorg xinit xterm virtualbox-guest-utils nomacs -y
fi

if [ "$1" == "i3" ]; then
        sudo apt install i3 terminator firefox dmenu thunar -y
        echo "exec i3" > /home/v/.xinitrc
        chown v:v /home/v/.xinitrc
fi

if [ "$1" == "gnome" ]; then
	sudo apt install gdm3 gnome-terminal -y
fi

if [ "$1" == "gdmon" ]; then
	#fix
	echo "don't need this... it's on"
	#sudo systemctl enable gdm
fi

if [ "$1" == "omz" ]; then
        sudo apt install git -y
        sudo apt install zsh wget -y
        sh -c "$(wget https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)"
        sed -i 's/robbyrussell/junkfood/g' ~/.zshrc
fi

if [ "$1" == "dev" ]; then
	sudo add-apt-repository ppa:webupd8team/atom -y
	sudo apt update -y
        sudo apt install git build-essential curl atom tmux -y
fi

if [ "$1" == "fixclock" ]; then
	#fix
	echo "don't need this... it's on, if clock is wrong, correct the /etc/localtime and reboot"
        #sudo apt install ntp -y
        #sudo ntpd -qg
        #sudo systemctl enable ntpd.service
        #sudo systemctl enable ntpd
fi

if [ "$1" == "neofetch" ]; then
	sudo add-apt-repository ppa:dawidd0811/neofetch-daily
  sudo apt update
  sudo apt install neofetch
	echo "neofetch" >> ~/.zshrc
fi

if [ "$1" == "min" ]; then
  ./devprep admin
  ./devprep.sh update
  ./devprep.sh X
  ./devprep.sh i3
  ./devprep.sh omz
  ./devprep.sh dev
  ./devprep.sh neofetch
  git clone https://github.com/jamesshane/i3groove
  cd i3groove
  ./install_requirements_ubuntu.sh
fi

if [ "$1" == "full" ]; then
  ./devprep admin
  ./devprep.sh update
  ./devprep.sh X
  ./devprep.sh i3
  ./devprep.sh gnome
  ./devprep.sh omz
  ./devprep.sh dev
  ./devprep.sh neofetch
  git clone https://github.com/jamesshane/i3groove
  cd i3groove
  ./install_requirements_ubuntu.sh
fi
