#!/bin/bash

if [ "$1" == "" ]; then
        echo "admin update X i3 gnome gdmon omz dev fixclock virtualbox-guest neofetch"
fi

if [ "$1" == "update" ]; then
	sudo apt update -y
	sudo apt upgrade -y
fi

if [ "$1" == "admin" ]; then
	apt install vim sudo -y
  visudo
  cp devprep /home/v/devprep.sh
  chown v:v /home/v/devprep.sh
fi

if [ "$1" == "X" ]; then
        sudo apt install xorg xinit xterm nomacs -y
fi

if [ "$1" == "i3" ]; then
        sudo apt install i3 terminator firefox-esr dmenu thunar -y
        echo "exec i3" > /home/v/.xinitrc
        chown v:v /home/v/.xinitrc
fi

if [ "$1" == "gnome" ]; then
	sudo apt install gdm3 gnome-terminal -y
fi

if [ "$1" == "gdmon" ]; then
	#fix
	echo "don't need this... it's on"
	#sudo systemctl enable gdm
fi

if [ "$1" == "omz" ]; then
        sudo apt install git -y
        sudo apt install zsh wget -y
        sh -c "$(wget https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)"
        sed -i 's/robbyrussell/junkfood/g' ~/.zshrc
fi

if [ "$1" == "dev" ]; then
  #sudo apt install tee -y
  sudo apt install wget -y
  wget https://atom.io/download/deb
  sudo dpkg -i deb
  sudo apt -y install -f
  rm deb
	sudo apt update -y
        sudo apt install git build-essential curl tmux -y
        wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | sudo apt-key add -
        sudo apt-get install apt-transport-https -y
        echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list
        sudo apt-get update -y
sudo apt-get install sublime-text -y
fi

if [ "$1" == "fixclock" ]; then
	#fix
	echo "don't need this... it's on, if clock is wrong, correct the /etc/localtime and reboot"
        #sudo apt install ntp -y
        #sudo ntpd -qg
        #sudo systemctl enable ntpd.service
        #sudo systemctl enable ntpd
fi

if [ "$1" == "virtualbox-guest" ]; then
  sudo apt install build-essential module-assistant dkms -y
  sudo m-a prepare
  echo "Do this as root: echo \"deb http://ftp.debian.org/debian jessie-backports main contrib\" >> /etc/apt/sources.list"
  echo "[then hit ENTER]"
  read kfkfkf
  sudo apt update
  sudo apt-get -t jessie-backports install virtualbox-guest-utils -y
fi

if [ "$1" == "neofetch" ]; then
	sudo add-apt-repository ppa:dawidd0811/neofetch-daily
  sudo apt update
  sudo apt install neofetch
	echo "neofetch" >> ~/.zshrc
fi

if [ "$1" == "min" ]; then
  ./devprep admin
  ./devprep.sh update
  ./devprep.sh X
  ./devprep.sh i3
  ./devprep.sh lightdm
  ./devprep.sh omz
  ./devprep.sh dev
  ./devprep.sh neofetch
  wget https://jamesshane.github.io/devprep/currentDev
  chmod +x currentDev
  wget https://jamesshane.github.io/devprep/gitprepGlobal
  chmod +x gitprepGlobal
  ./gitprepGlobal
  ./currentDev
  cd ~/projects/i3groove
  ./install_requirements_debian.sh
  cd ~/projects/JamesLinuxDevSetup
  ./MakeItSo.sh -v
fi

if [ "$1" == "full" ]; then
  ./devprep admin
  ./devprep.sh update
  ./devprep.sh X
  ./devprep.sh i3
  ./devprep.sh gnome
  ./devprep.sh omz
  ./devprep.sh dev
  ./devprep.sh neofetch
  wget https://jamesshane.github.io/devprep/currentDev
  chmod +x currentDev
  wget https://jamesshane.github.io/devprep/gitprepGlobal
  chmod +x gitprepGlobal
  ./gitprepGlobal
  ./currentDev
  cd ~/projects/i3groove
  ./install_requirements_debian.sh
  cd ~/projects/JamesLinuxDevSetup
  ./MakeItSo.sh -v
fi
