#!/bin/bash

if [ "$1" == "" ]; then
        echo "update admin X i3 gnome gdmon omz dev fixclock virtualbox-guest"
fi

if [ "$1" == "update" ]; then
	sudo apt update -y
	sudo apt upgrade -y
fi

if [ "$1" == "admin" ]; then
	apt install vim sudo -y
  visudo
fi

if [ "$1" == "X" ]; then
        sudo apt install xorg xinit xterm -y
fi

if [ "$1" == "i3" ]; then
        sudo apt install i3 terminator firefox-esr dmenu thunar -y
        echo "exec i3" > /home/v/.xinitrc
        chown v:v /home/v/.xinitrc
fi

if [ "$1" == "gnome" ]; then
	sudo apt install gdm3 gnome-terminal -y
fi

if [ "$1" == "gdmon" ]; then
	#fix
	echo "don't need this... it's on"
	#sudo systemctl enable gdm
fi

if [ "$1" == "omz" ]; then
        sudo apt install git -y
        sudo apt install zsh wget -y
        sh -c "$(wget https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)"
        sed -i 's/robbyrussell/junkfood/g' ~/.zshrc
fi

if [ "$1" == "dev" ]; then
  sudo apt install wget -y
  wget https://atom.io/download/deb
  sudo dpkg -i atom-amd64.deb
  sudo apt -y install -f
  rm deb
	sudo apt update -y
        sudo apt install git build-essential curl tmux -y
fi

if [ "$1" == "fixclock" ]; then
	#fix
	echo "don't need this... it's on, if clock is wrong, correct the /etc/localtime and reboot"
        #sudo apt install ntp -y
        #sudo ntpd -qg
        #sudo systemctl enable ntpd.service
        #sudo systemctl enable ntpd
fi

if [ "$1" == "virtualbox-guest" ]; then
  sudo apt install build-essential module-assistant dkms
  sudo m-a prepare
  echo "Do this as root: echo \"deb http://ftp.debian.org/debian jessie-backports main contrib\" >> /etc/apt/sources.list"
  echo "[then hit ENTER]"
  read kfkfkf
  sudo apt update
  sudo apt-get -t jessie-backports install virtualbox-guest-utils
fi
