#!/bin/bash

if [ "$1" == "" ]; then
	echo "update archfi admin X i3 gnome gdmon omz dev fixclock yaourt neofetch"
fi

if [ "$1" == "update" ]; then
	sudo pacman -Syy
fi

if [ "$1" == "archfi" ]; then
	wget archfi.sf.net/archfi
	sh archfi
fi

if [ "$1" == "admin" ]; then
	useradd -m -d /home/v v
	passwd v
	pacman -Sy
	pacman -S sudo openssh
	visudo
	cp devprep /home/v/devprep.sh
	chown v:v /home/v/devprep.sh
	chmod +x /home/v/devprep.sh
fi

if [ "$1" == "X" ]; then
	sudo pacman -S xorg xorg-xinit xterm virtualbox-guest-utils
fi

if [ "$1" == "i3" ]; then
	sudo pacman -S i3 terminator firefox dmenu thunar
	echo "exec i3" > /home/v/.xinitrc
	chown v:v /home/v/.xinitrc
fi

if [ "$1" == "gnome" ]; then
	sudo pacman -S gnome
fi

if [ "$1" == "gdmon" ]; then
	sudo systemctl enable gdm
fi

if [ "$1" == "omz" ]; then
	sudo pacman -S git
	sudo pacman -S zsh wget
	sh -c "$(wget https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)"
	sed -i 's/robbyrussell/junkfood/g' ~/.zshrc
fi

if [ "$1" == "dev" ]; then
	sudo pacman -S git base-devel curl atom tmux
fi

if [ "$1" == "fixclock" ]; then
	sudo pacman -S ntp
	sudo ntpd -qg
	sudo systemctl enable ntpd.service
	sudo systemctl enable ntpd
fi

if [ "$1" == "yaourt" ]; then
	git clone https://aur.archlinux.org/package-query.git
	cd package-query
	makepkg -si
	cd ..
	git clone https://aur.archlinux.org/yaourt.git
	cd yaourt
	makepkg -si
	cd ..
fi

if [ "$1" == "neofetch" ]; then
	sudo pacman -S neofetch
fi
